"""
Seed Data — 8 Kategori + 64 DUS Sorusu
"""

CATEGORIES = [
    {"id": 1, "name": "Oral Diagnoz ve Radyoloji", "description": "Ağız içi muayene, radyografik değerlendirme ve teşhis yöntemleri", "icon": "🔍", "color": "#FF6B6B"},
    {"id": 2, "name": "Periodontoloji", "description": "Diş eti hastalıkları, periodontal tedavi ve cerrahi", "icon": "🦷", "color": "#4ECDC4"},
    {"id": 3, "name": "Endodonti", "description": "Kanal tedavisi, pulpa hastalıkları ve kök ucu tedavileri", "icon": "💉", "color": "#45B7D1"},
    {"id": 4, "name": "Ortodonti", "description": "Diş ve çene düzensizlikleri, ortodontik tedavi yöntemleri", "icon": "😁", "color": "#96CEB4"},
    {"id": 5, "name": "Protetik Diş Tedavisi", "description": "Sabit ve hareketli protezler, implant üstü protezler", "icon": "🔧", "color": "#FFEAA7"},
    {"id": 6, "name": "Pedodonti", "description": "Çocuk diş hekimliği, süt dişleri ve koruyucu uygulamalar", "icon": "👶", "color": "#DDA0DD"},
    {"id": 7, "name": "Ağız, Diş ve Çene Cerrahisi", "description": "Diş çekimi, implant cerrahisi, çene kırıkları", "icon": "🏥", "color": "#98D8C8"},
    {"id": 8, "name": "Restoratif Diş Tedavisi", "description": "Dolgu, inley, onley, estetik restorasyonlar", "icon": "✨", "color": "#F7DC6F"},
]

QUESTIONS = [
    # ═══════════════════════════════════════
    # KATEGORİ 1: Oral Diagnoz ve Radyoloji
    # ═══════════════════════════════════════
    {"category_id":1,"question_text":"Panoramik radyografide en sık görülen artefakt hangisidir?","option_a":"Hayalet görüntü","option_b":"Çift görüntü","option_c":"Hava boşluğu artefaktı","option_d":"Metal artefakt","option_e":"Hareket bulanıklığı","correct_answer":"A","explanation":"Panoramik radyografide karşı taraftaki yapıların yansıma olarak görülmesi 'hayalet görüntü (ghost image)' olarak adlandırılır ve en sık karşılaşılan artefakttır.","difficulty":"orta","source":"Oral Radyoloji, White & Pharoah"},
    {"category_id":1,"question_text":"Periapikal radyografide kök ucunda sınırları belirgin, yuvarlak radyolüsent lezyon görülmektedir. En olası tanı nedir?","option_a":"Periapikal granülom","option_b":"Periapikal kist","option_c":"Periapikal apse","option_d":"Sementoma","option_e":"Fibröz displazi","correct_answer":"B","explanation":"Sınırları belirgin, yuvarlak radyolüsent lezyon periapikal kist ile uyumludur. Granülomda sınırlar daha belirsiz olabilir.","difficulty":"orta","source":"Oral Diagnoz"},
    {"category_id":1,"question_text":"Oral mukozada beyaz, kazınabilen lezyon hangisidir?","option_a":"Lökoplaki","option_b":"Liken planus","option_c":"Kandida enfeksiyonu","option_d":"Beyaz süngersi nevüs","option_e":"Fordyce granülleri","correct_answer":"C","explanation":"Kandida (pseudomembranöz tip) kazınabilen beyaz plaklar oluşturur. Lökoplaki ve liken planus kazınamaz.","difficulty":"kolay","source":"Oral Patoloji"},
    {"category_id":1,"question_text":"Sjögren sendromunda hangi bulgu beklenmez?","option_a":"Ağız kuruluğu","option_b":"Göz kuruluğu","option_c":"Parotis büyümesi","option_d":"Dilde hipersalivasyon","option_e":"Artrit","correct_answer":"D","explanation":"Sjögren sendromu bir otoimmün hastalıktır ve tükürük/gözyaşı bezlerini etkiler. Hipersalivasyon değil, ağız kuruluğu (kserostomi) beklenir.","difficulty":"kolay","source":"İç Hastalıkları - Otoimmün"},
    {"category_id":1,"question_text":"Aşağıdakilerden hangisi malign transformasyon riski en yüksek olan premalign lezyondur?","option_a":"Lökoplaki","option_b":"Eritroplaki","option_c":"Liken planus","option_d":"Oral submüköz fibrozis","option_e":"Aktinik keratoz","correct_answer":"B","explanation":"Eritroplaki, oral premalign lezyonlar arasında malign transformasyon riski en yüksek olandır (%14-50). Lökoplaki'de bu oran %1-9 civarındadır.","difficulty":"zor","source":"Oral Patoloji"},
    {"category_id":1,"question_text":"CBCT (Konik Işınlı Bilgisayarlı Tomografi) hangi durumda öncelikle endikedir?","option_a":"Rutin diş çürüğü tespiti","option_b":"İmplant planlama","option_c":"Periodontal cep ölçümü","option_d":"Oklüzyon analizi","option_e":"Tükürük bezi taşı","correct_answer":"B","explanation":"CBCT, 3 boyutlu görüntüleme sağladığı için özellikle implant planlama, gömülü dişler ve çene patolojilerinde endikedir.","difficulty":"kolay","source":"Oral Radyoloji"},
    {"category_id":1,"question_text":"Bisfosfanat kullanan hastada diş çekimi sonrası en çok korkulan komplikasyon nedir?","option_a":"Alveolar osteit","option_b":"Osteonekroz","option_c":"Kanama","option_d":"Enfeksiyon","option_e":"Sinir hasarı","correct_answer":"B","explanation":"Bisfosfanat ilişkili çene osteonekrozu (BRONJ/MRONJ) en önemli komplikasyondur. Kemik iyileşmesi bozulur ve nekroz gelişir.","difficulty":"zor","source":"Oral Cerrahi"},
    {"category_id":1,"question_text":"Aşağıdakilerden hangisi odontojenik bir tümördür?","option_a":"Ameloblastom","option_b":"Osteom","option_c":"Fibrom","option_d":"Hemanjiyom","option_e":"Nörofibrom","correct_answer":"A","explanation":"Ameloblastom, diş oluşum dokularından (odontojenik epitel) kaynaklanan en yaygın odontojenik tümördür.","difficulty":"orta","source":"Oral Patoloji"},

    # ═══════════════════════════════════════
    # KATEGORİ 2: Periodontoloji
    # ═══════════════════════════════════════
    {"category_id":2,"question_text":"Periodontal hastalığın primer etyolojik faktörü nedir?","option_a":"Genetik yatkınlık","option_b":"Mikrobiyal dental plak","option_c":"Travmatik oklüzyon","option_d":"Sigara kullanımı","option_e":"Diabetes mellitus","correct_answer":"B","explanation":"Periodontal hastalığın birincil nedeni mikrobiyal dental plaktır. Diğer faktörler (sigara, diyabet, genetik) hastalığın seyrini etkileyen risk faktörleridir.","difficulty":"kolay","source":"Klinik Periodontoloji, Carranza"},
    {"category_id":2,"question_text":"Aşağıdakilerden hangisi periodontal cebin klinik göstergesidir?","option_a":"Dişeti çekilmesi","option_b":"Sondalamada kanama","option_c":"Diş mobilitesi","option_d":"Dişeti hiperplazisi","option_e":"Alveol kemik kaybı","correct_answer":"B","explanation":"Sondalama kanamama (BOP) periodontal inflamasyonun ve aktif periodontal cebin en güvenilir klinik göstergesidir.","difficulty":"orta","source":"Klinik Periodontoloji"},
    {"category_id":2,"question_text":"Agresif periodontitisin karakteristik özelliği hangisidir?","option_a":"Yaşlı bireylerde görülür","option_b":"Yavaş ilerleme gösterir","option_c":"Sistemik olarak sağlıklı bireylerde hızlı kemik kaybı","option_d":"Sadece alt çenede görülür","option_e":"Plak birikimi ile orantılı yıkım","correct_answer":"C","explanation":"Agresif periodontitis, sistemik olarak sağlıklı genç bireylerde plak miktarı ile orantısız hızlı ataşman ve kemik kaybı ile karakterizedir.","difficulty":"orta","source":"Periodontoloji"},
    {"category_id":2,"question_text":"Flap operasyonunun amacı nedir?","option_a":"Diş beyazlatma","option_b":"Kök yüzeyine erişim ve temizlik","option_c":"Dolgu yapımı","option_d":"Kanal tedavisi","option_e":"Diş çekimi","correct_answer":"B","explanation":"Flap cerrahisi, derin periodontal ceplerde kök yüzeyine doğrudan görüş ve erişim sağlayarak debridman ve defekt tedavisi imkanı verir.","difficulty":"kolay","source":"Periodontoloji"},
    {"category_id":2,"question_text":"GTR (Guided Tissue Regeneration) membranının amacı nedir?","option_a":"Kanama kontrolü","option_b":"Enfeksiyonu önleme","option_c":"Epitel hücrelerinin defekte göçünü engelleme","option_d":"Kemik greftini sabitlme","option_e":"Ağrı kontrolü","correct_answer":"C","explanation":"GTR membranı, hızlı çoğalan epitel ve bağ dokusu hücrelerinin defekt bölgesine göçünü engelleyerek periodontal ligament hücrelerinin rejenere olmasına zaman tanır.","difficulty":"zor","source":"Periodontal Rejenerasyon"},
    {"category_id":2,"question_text":"Diş taşı (kalkülüs) oluşumunda en önemli mineral hangisidir?","option_a":"Kalsiyum fosfat","option_b":"Demir oksit","option_c":"Sodyum klorür","option_d":"Potasyum karbonat","option_e":"Magnezyum sülfat","correct_answer":"A","explanation":"Diş taşı ağırlıklı olarak kalsiyum fosfat minerallerinden (hidroksiapatit, oktakalsiyum fosfat) oluşur.","difficulty":"kolay","source":"Periodontoloji"},
    {"category_id":2,"question_text":"Aşağıdakilerden hangisi periodontal hastalık için sistemik risk faktörüdür?","option_a":"Çay tüketimi","option_b":"Diabetes mellitus","option_c":"Hipertansiyon","option_d":"Anemi","option_e":"Hipotiroidi","correct_answer":"B","explanation":"Diabetes mellitus, periodontal hastalık için kanıtlanmış en önemli sistemik risk faktörüdür. İki hastalık arasında çift yönlü ilişki vardır.","difficulty":"orta","source":"Periodontoloji"},
    {"category_id":2,"question_text":"Klinik ataşman kaybı nasıl ölçülür?","option_a":"Dişeti kenarından cep tabanına","option_b":"Mine-sement birleşiminden cep tabanına","option_c":"Kemik kretinden cep tabanına","option_d":"İnsizal kenardan cep tabanına","option_e":"Dişeti kenarından kemik kretine","correct_answer":"B","explanation":"Klinik ataşman kaybı (CAL), mine-sement birleşimi (CEJ) referans noktasından cep/sulkus tabanına kadar olan mesafedir.","difficulty":"orta","source":"Klinik Periodontoloji"},

    # ═══════════════════════════════════════
    # KATEGORİ 3: Endodonti
    # ═══════════════════════════════════════
    {"category_id":3,"question_text":"İrreversibl pulpitiste en karakteristik semptom hangisidir?","option_a":"Soğuğa kısa süreli hassasiyet","option_b":"Spontan, uzun süren ve yayılan ağrı","option_c":"Perküsyonda hassasiyet","option_d":"Isıya hassasiyet yok","option_e":"Ağrısız şişlik","correct_answer":"B","explanation":"İrreversibl pulpitiste spontan başlayan, uzun süren (uyaran kalktıktan sonra da devam eden) ve bazen yayılan ağrı karakteristiktir.","difficulty":"orta","source":"Endodonti, Cohen"},
    {"category_id":3,"question_text":"Kanal tedavisinde çalışma boyu nasıl belirlenir?","option_a":"Sadece radyografi ile","option_b":"Elektronik apeks bulucu + radyografi","option_c":"Taktil his ile","option_d":"Sadece elektronik apeks bulucu","option_e":"Diş boyuna göre tahmin","correct_answer":"B","explanation":"Çalışma boyu belirlenmesinde elektronik apeks bulucu ile ölçüm yapılır ve radyografi ile doğrulanır. İki yöntemin kombinasyonu en güvenilir sonucu verir.","difficulty":"kolay","source":"Endodonti"},
    {"category_id":3,"question_text":"Kök kanal şekillendirmesinde 'step-back' tekniğinin amacı nedir?","option_a":"Kanalı düzleştirmek","option_b":"Apikal bölgeden koronale doğru genişletme","option_c":"Koronalden apikale doğru genişletme","option_d":"Sadece apikal bölgeyi şekillendirme","option_e":"Sadece koronal bölgeyi genişletme","correct_answer":"B","explanation":"Step-back tekniğinde apikal bölgede master apikal eğe ile çalışılır, sonra her numara artışında 1 mm kısaltılarak koronale doğru genişletilir.","difficulty":"zor","source":"Endodonti"},
    {"category_id":3,"question_text":"Sodyum hipoklorit (NaOCl) kanal irrigasyonunda neden kullanılır?","option_a":"Smear tabakasını çözer","option_b":"Organik doku çözücü ve antimikrobiyal","option_c":"Kanalı genişletir","option_d":"Anestezi sağlar","option_e":"Kanal duvarını sertleştirir","correct_answer":"B","explanation":"NaOCl güçlü bir organik doku çözücü ve geniş spektrumlu antimikrobiyal ajandır. Smear tabakasını çözmez (bunun için EDTA kullanılır).","difficulty":"kolay","source":"Endodonti"},
    {"category_id":3,"question_text":"Aşağıdakilerden hangisi vital pulpa tedavisi değildir?","option_a":"Direkt kuafaj","option_b":"İndirekt kuafaj","option_c":"Pulpotomi","option_d":"Pulpektomi","option_e":"Apeksogenez","correct_answer":"D","explanation":"Pulpektomi, pulpanın tamamının çıkarılmasıdır (kanal tedavisi). Diğerleri pulpanın canlılığını korumayı amaçlayan vital tedavilerdir.","difficulty":"kolay","source":"Endodonti"},
    {"category_id":3,"question_text":"MTA (Mineral Trioxide Aggregate) hangi durumda kullanılmaz?","option_a":"Perforasyon tamiri","option_b":"Direkt kuafaj","option_c":"Retrograd dolgu","option_d":"Kanal dolgusu pat olarak","option_e":"Apeksifikasyon","correct_answer":"D","explanation":"MTA perforasyon, kuafaj, retrograd dolgu ve apeksifikasyonda kullanılır. Ancak sertleşme süresi uzun ve manipülasyonu zor olduğu için rutin kanal dolgu patı olarak tercih edilmez.","difficulty":"zor","source":"Endodonti"},
    {"category_id":3,"question_text":"İnternal rezorpsiyonun en önemli radyografik bulgusu nedir?","option_a":"Kök ucunda radyolüsens","option_b":"Kanal lümeninin düzgün sınırlı genişlemesi","option_c":"Lamina duranın kaybı","option_d":"Kök kısalması","option_e":"Periapikal skleroz","correct_answer":"B","explanation":"İnternal rezorpsiyonda granülasyon dokusu kök kanalı içinde rezorpsiyona neden olur ve radyografide kanal lümeninin düzgün sınırlı, balon şeklinde genişlemesi görülür.","difficulty":"orta","source":"Endodonti"},
    {"category_id":3,"question_text":"Kanal tedavisinde obtürasyon için en yaygın kullanılan materyal hangisidir?","option_a":"Amalgam","option_b":"Kompozit rezin","option_c":"Gutta-perka","option_d":"Cam iyonomer","option_e":"Çinko oksit öjenol","correct_answer":"C","explanation":"Gutta-perka, biyouyumlu, radyoopak, boyutsal olarak stabil ve gerektiğinde çıkarılabilir olması nedeniyle kanal obtürasyonunda altın standarttır.","difficulty":"kolay","source":"Endodonti"},

    # ═══════════════════════════════════════
    # KATEGORİ 4: Ortodonti
    # ═══════════════════════════════════════
    {"category_id":4,"question_text":"Angle Sınıf II Bölüm 1 maloklüzyonun karakteristik özelliği nedir?","option_a":"Alt çene protrüzyonu","option_b":"Üst kesici dişlerin proklinasyonu ve artmış overjet","option_c":"Anterior çapraz kapanış","option_d":"Üst kesicilerin retroklinasyonu","option_e":"Normal overjet","correct_answer":"B","explanation":"Sınıf II Bölüm 1'de üst birinci molar alt birinciye göre mezializedir ve üst kesiciler prokline (öne eğik) olup overjet artmıştır.","difficulty":"orta","source":"Ortodonti, Proffit"},
    {"category_id":4,"question_text":"Sefalometrik analizde SNA açısı neyi değerlendirir?","option_a":"Alt çenenin konumu","option_b":"Üst çenenin kafatasına göre sagittal konumu","option_c":"Üst ve alt çene ilişkisi","option_d":"Yüz yüksekliği","option_e":"Diş inklinasyonu","correct_answer":"B","explanation":"SNA açısı (Sella-Nasion-A noktası), maksillerin (üst çene) kafa tabanına göre anteroposterior konumunu değerlendirir. Normal değeri 82°±2'dir.","difficulty":"orta","source":"Sefalometri"},
    {"category_id":4,"question_text":"Fonksiyonel ortodontik apareyler hangi dönemde en etkilidir?","option_a":"Süt dişlenme döneminde","option_b":"Aktif büyüme döneminde (puberte)","option_c":"Erişkin dönemde","option_d":"Doğum sonrası ilk yıl","option_e":"Büyüme tamamlandıktan sonra","correct_answer":"B","explanation":"Fonksiyonel apareyler (Aktivatör, Twin Block vb.) iskeletsel büyümeyi yönlendirmeyi amaçlar ve aktif büyüme döneminde (pubertal growth spurt) en etkilidir.","difficulty":"kolay","source":"Ortodonti"},
    {"category_id":4,"question_text":"Ortodontik tedavide en sık kullanılan kuvvet tipi hangisidir?","option_a":"Ağır kesikli kuvvet","option_b":"Hafif sürekli kuvvet","option_c":"Ağır sürekli kuvvet","option_d":"Orta kesikli kuvvet","option_e":"Aralıklı kuvvet","correct_answer":"B","explanation":"Ortodontik diş hareketi için optimal kuvvet, hafif ve sürekli kuvvettir. Bu kuvvet fizyolojik kemik remodelingini tetikler ve kök rezorpsiyonu riskini minimize eder.","difficulty":"kolay","source":"Ortodonti"},
    {"category_id":4,"question_text":"Maksiller ekspansiyon (RME) apareyinin temel etki mekanizması nedir?","option_a":"Dişlerin devrilmesi","option_b":"Midpalatal sütürün açılması","option_c":"Alveoler kemiğin büyümesi","option_d":"Dişlerin intrüzyonu","option_e":"Çene kemiğinin rezorpsiyonu","correct_answer":"B","explanation":"Hızlı maksiller ekspansiyon (RME), midpalatal sütüre ortopedik kuvvet uygulayarak sütürü açar ve üst çeneyi genişletir. Büyüme döneminde en etkilidir.","difficulty":"orta","source":"Ortodonti"},
    {"category_id":4,"question_text":"Headgear (ekstraoral aparey) hangi durumda endikedir?","option_a":"Mandibular retrognatide","option_b":"Maksiller prognatide / Sınıf II düzeltmede","option_c":"Alt çenenin ilerletilmesinde","option_d":"Anterior açık kapanışta","option_e":"Tek diş rotasyonunda","correct_answer":"B","explanation":"Headgear üst çeneye ve/veya üst dişlere distalizasyon kuvveti uygulayarak Sınıf II ilişkiyi düzeltmek ve maksiller büyümeyi kontrol etmek için kullanılır.","difficulty":"orta","source":"Ortodonti"},
    {"category_id":4,"question_text":"Retansiyon döneminde en yaygın kullanılan aparey hangisidir?","option_a":"Aktivatör","option_b":"Hawley retainer","option_c":"Herbst aparey","option_d":"Quad helix","option_e":"Nance apareyi","correct_answer":"B","explanation":"Hawley retainer, akrilik tabanlı ve labial yay içeren, aktif tedavi sonrası dişlerin pozisyonunu korumak için en yaygın kullanılan çıkarılabilir retainerdir.","difficulty":"kolay","source":"Ortodonti"},
    {"category_id":4,"question_text":"Ortodontik diş hareketinde basınç tarafında ne olur?","option_a":"Kemik yapımı (apozisyon)","option_b":"Kemik yıkımı (rezorpsiyon)","option_c":"Sement yapımı","option_d":"Pulpa nekrozu","option_e":"Kök uzaması","correct_answer":"B","explanation":"Ortodontik kuvvet uygulandığında basınç tarafında osteoklastlar aktive olarak kemik rezorpsiyonu, çekim tarafında ise osteoblastlar ile kemik apozisyonu gerçekleşir.","difficulty":"orta","source":"Ortodonti"},

    # ═══════════════════════════════════════
    # KATEGORİ 5: Protetik Diş Tedavisi
    # ═══════════════════════════════════════
    {"category_id":5,"question_text":"Tam seramik restorasyonlar için en ideal preparasyon şekli hangisidir?","option_a":"Chamfer/shoulder basamak","option_b":"Knife-edge (bıçak sırtı)","option_c":"Basamaksız (feather-edge)","option_d":"Beveled shoulder","option_e":"Preparasyon gerektirmez","correct_answer":"A","explanation":"Tam seramik restorasyonlar kırılgan olduğundan yeterli kalınlık için chamfer veya shoulder basamak gerekir. Knife-edge yeterli materyal kalınlığı sağlamaz.","difficulty":"orta","source":"Sabit Protez, Shillingburg"},
    {"category_id":5,"question_text":"Hareketli bölümlü protezde Kennedy Sınıf I nedir?","option_a":"Tek taraflı posterior dişsiz bölge","option_b":"Bilateral posterior serbest sonlu dişsiz bölge","option_c":"Anterior dişsiz bölge","option_d":"Bilateral anterior dişsiz bölge","option_e":"Tek diş eksikliği","correct_answer":"B","explanation":"Kennedy Sınıf I, her iki tarafta da en posterior dişlerin arkasında serbest sonlu (distal extension) dişsiz bölge olan sınıflamadır.","difficulty":"orta","source":"Hareketli Protez"},
    {"category_id":5,"question_text":"İmplant üstü protezlerde osseoentegrasyon süresi ortalama ne kadardır?","option_a":"1 hafta","option_b":"2-4 hafta","option_c":"3-6 ay","option_d":"1 yıl","option_e":"2 yıl","correct_answer":"C","explanation":"Osseoentegrasyon (implant-kemik birleşmesi) alt çenede ortalama 3 ay, üst çenede kemik kalitesine bağlı olarak 4-6 ay sürer.","difficulty":"kolay","source":"İmplantoloji"},
    {"category_id":5,"question_text":"Sabit protezde biyolojik genişlik ihlali ne sonuç doğurur?","option_a":"Retansiyon artışı","option_b":"Kronik dişeti iltihabı ve kemik kaybı","option_c":"Estetik iyileşme","option_d":"Pulpa canlılığının korunması","option_e":"Çürük oluşumunun azalması","correct_answer":"B","explanation":"Biyolojik genişlik (junctional epitel + bağ dokusu ataşmanı ≈2mm) ihlal edilirse vücut bu mesafeyi yeniden oluşturmak için kemik rezorpsiyonu yapar ve kronik inflamasyon gelişir.","difficulty":"zor","source":"Periodontal Protetik"},
    {"category_id":5,"question_text":"Aşağıdakilerden hangisi ölçü maddesi değildir?","option_a":"Aljinat","option_b":"Polivinilsiloksan","option_c":"Çinko fosfat siman","option_d":"Polieter","option_e":"Silikon","correct_answer":"C","explanation":"Çinko fosfat siman bir yapıştırma simanıdır, ölçü maddesi değildir. Diğerleri farklı tiplerde elastik ölçü materyalleridir.","difficulty":"kolay","source":"Protetik"},
    {"category_id":5,"question_text":"Metal destekli porselen restorasyonda opak tabakasının amacı nedir?","option_a":"Bağlanma gücünü artırmak","option_b":"Metal alt yapının rengini maskelemek","option_c":"Restorasyonu güçlendirmek","option_d":"Isı iletimini azaltmak","option_e":"Çürük önlemek","correct_answer":"B","explanation":"Opak tabaka, koyu renkli metal alt yapıyı maskeleyerek porselen restorasyonun doğal diş rengini taklit etmesini sağlar.","difficulty":"kolay","source":"Sabit Protez"},
    {"category_id":5,"question_text":"Tam protezde 'post-dam' alanının işlevi nedir?","option_a":"Estetik sağlama","option_b":"Posterior palatal seal — protez retansiyonunu artırma","option_c":"Konuşmayı düzeltme","option_d":"Çiğneme kuvvetini dağıtma","option_e":"Damak refleksini engelleme","correct_answer":"B","explanation":"Post-dam (posterior palatal seal), üst tam protezin arka kenarında yapılan vurgulama ile periferik seal sağlayarak protezin retansiyonunu artırır.","difficulty":"orta","source":"Tam Protez"},
    {"category_id":5,"question_text":"CAD/CAM ile üretilen restorasyonların en önemli avantajı nedir?","option_a":"Düşük maliyet","option_b":"Yüksek hassasiyet ve tekrarlanabilirlik","option_c":"Sürekli polisaj","option_d":"Radyoopak görünüm","option_e":"Biyoaktif salınım","correct_answer":"B","explanation":"CAD/CAM teknolojisi dijital tarama ve bilgisayar kontrollü üretim ile yüksek hassasiyet, tutarlı kalite ve standardize edilebilir üretim imkanı sağlar.","difficulty":"orta","source":"Dijital Diş Hekimliği"},

    # ═══════════════════════════════════════
    # KATEGORİ 6: Pedodonti
    # ═══════════════════════════════════════
    {"category_id":6,"question_text":"Süt dişlerinin sürmesi hangi yaşta başlar?","option_a":"3 ay","option_b":"6 ay","option_c":"12 ay","option_d":"18 ay","option_e":"24 ay","correct_answer":"B","explanation":"İlk süt dişleri (genellikle alt santral kesiciler) ortalama 6. ayda sürmeye başlar. 2.5-3 yaş civarında süt dişlenme tamamlanır.","difficulty":"kolay","source":"Pedodonti"},
    {"category_id":6,"question_text":"Çocuklarda diş travmasında en sık etkilenen diş hangisidir?","option_a":"Üst santral kesiciler","option_b":"Alt santral kesiciler","option_c":"Üst kanin dişler","option_d":"Alt premolar dişler","option_e":"Üst lateral kesiciler","correct_answer":"A","explanation":"Çocuklarda diş travması en sık üst santral kesici dişleri etkiler. Protrüziv pozisyonları nedeniyle travmaya en açık dişlerdir.","difficulty":"kolay","source":"Pedodonti"},
    {"category_id":6,"question_text":"Fissür örtücü (sealant) uygulaması için en ideal zaman hangisidir?","option_a":"Süt dişlenme döneminde","option_b":"Dişin tam sürdüğü andan itibaren","option_c":"Erişkin dönemde","option_d":"Çürük oluştuktan sonra","option_e":"Diş düştükten sonra","correct_answer":"B","explanation":"Fissür örtücüler, daimi dişler (özellikle 1. molarlar) tam sürdükten sonra, çürük oluşmadan önce, fissürlerin en savunmasız olduğu dönemde uygulanmalıdır.","difficulty":"kolay","source":"Koruyucu Diş Hekimliği"},
    {"category_id":6,"question_text":"Çocuk hastada davranış yönetiminde 'tell-show-do' tekniğinin ilk adımı nedir?","option_a":"Uygulamayı yapmak","option_b":"Uygulamayı göstermek","option_c":"Uygulamayı açıklamak (anlatmak)","option_d":"Çocuğu ödüllendirmek","option_e":"Ebeveyne anlatmak","correct_answer":"C","explanation":"Tell-Show-Do tekniğinde önce yapılacak işlem çocuğun anlayacağı dilde anlatılır (Tell), sonra gösterilir (Show), en son uygulanır (Do).","difficulty":"kolay","source":"Pedodonti - Davranış Yönetimi"},
    {"category_id":6,"question_text":"Süt dişi pulpotomisinde en yaygın kullanılan medikament hangisidir?","option_a":"Kalsiyum hidroksit","option_b":"Formokrezol","option_c":"Antibiyotik pat","option_d":"Çinko oksit öjenol","option_e":"MTA","correct_answer":"E","explanation":"Güncel pedodonti pratiğinde MTA (Mineral Trioxide Aggregate), biyouyumluluğu ve başarı oranının yüksekliği nedeniyle süt dişi pulpotomisinde tercih edilen materyaldir. Formokrezol geleneksel olarak kullanılmış ancak toksisitesi nedeniyle yerini MTA'ya bırakmaktadır.","difficulty":"orta","source":"Pedodonti"},
    {"category_id":6,"question_text":"Yer tutucu aparey hangi durumda endikedir?","option_a":"Süt dişinin fizyolojik olarak düşmesinden sonra","option_b":"Süt dişinin erken kaybı sonrası daimi dişin sürmesine kadar","option_c":"Daimi diş sürdükten sonra","option_d":"Ortodontik tedavi sırasında","option_e":"Her diş çekiminden sonra","correct_answer":"B","explanation":"Yer tutucu, süt dişinin zamanından önce kaybedilmesi durumunda, komşu dişlerin kayarak daimi dişin süreceği alanı kapatmasını engellemek için kullanılır.","difficulty":"orta","source":"Pedodonti"},
    {"category_id":6,"question_text":"Natal diş nedir?","option_a":"Süt dişinin geç sürmesi","option_b":"Doğumda ağızda bulunan diş","option_c":"Fazla sayıda diş","option_d":"Gömülü diş","option_e":"Daimi dişin erken sürmesi","correct_answer":"B","explanation":"Natal diş, doğumda ağız içinde zaten sürmesin durumda olan diştir. Neonatal diş ise doğumdan sonraki ilk 30 gün içinde süren diştir.","difficulty":"orta","source":"Pedodonti"},
    {"category_id":6,"question_text":"Çocuklarda topikal flor uygulamasının temel koruyucu mekanizması nedir?","option_a":"Bakterileri öldürmek","option_b":"Mine kristallerinde floroapatit oluşumu","option_c":"Tükürük akışını artırmak","option_d":"Diş beyazlatma","option_e":"Plak oluşumunu engellemek","correct_answer":"B","explanation":"Topikal flor, mine yüzeyindeki hidroksiapatit kristallerini daha asit dirençli floroapatite dönüştürerek çürüğe karşı koruma sağlar.","difficulty":"orta","source":"Koruyucu Diş Hekimliği"},

    # ═══════════════════════════════════════
    # KATEGORİ 7: Ağız, Diş ve Çene Cerrahisi
    # ═══════════════════════════════════════
    {"category_id":7,"question_text":"Diş çekiminde en sık görülen komplikasyon hangisidir?","option_a":"Çene kırığı","option_b":"Alveoler osteit (kuru soket)","option_c":"Sinir hasarı","option_d":"Maksillar sinüs perforasyonu","option_e":"Komşu diş hasarı","correct_answer":"B","explanation":"Alveoler osteit (dry socket), diş çekimi sonrası pıhtının bozulması ile ortaya çıkan en sık komplikasyondur. Özellikle alt yirmi yaş dişi çekimlerinde görülür.","difficulty":"kolay","source":"Oral Cerrahi"},
    {"category_id":7,"question_text":"Alt yirmi yaş dişi çekiminde en çok risk altında olan sinir hangisidir?","option_a":"Nervus facialis","option_b":"Nervus alveolaris inferior","option_c":"Nervus opticus","option_d":"Nervus vagus","option_e":"Nervus hypoglossus","correct_answer":"B","explanation":"Alt yirmi yaş (3. molar) dişi kökleri nervus alveolaris inferior'a yakın seyrettiğinden, cerrahi çekim sırasında bu sinir en çok risk altındadır.","difficulty":"orta","source":"Oral Cerrahi"},
    {"category_id":7,"question_text":"Lokal anestezide en sık kullanılan vazokonstriktör hangisidir?","option_a":"Norepinefrin","option_b":"Epinefrin (Adrenalin)","option_c":"Felipressin","option_d":"Dopamin","option_e":"Serotonin","correct_answer":"B","explanation":"Epinefrin (adrenalin), lokal anesteziklere eklenen en yaygın vazokonstriktördür. Anestezi süresini uzatır, kanama kontrolü sağlar ve anestezik maddenin emilimini yavaşlatır.","difficulty":"kolay","source":"Lokal Anestezi"},
    {"category_id":7,"question_text":"Le Fort I kırığı hangi seviyede oluşur?","option_a":"Orbita tabanı seviyesinde","option_b":"Maksilla alt seviyesinde (piriform apertura)","option_c":"Zigoma ve orbita seviyesinde","option_d":"Kafa tabanı seviyesinde","option_e":"Mandibula seviyesinde","correct_answer":"B","explanation":"Le Fort I (Guerin kırığı) maksiller alveolar proçesin piriform apertura seviyesinde yatay kırığıdır. Le Fort II piramidal, Le Fort III kraniyofasyal ayrılmadır.","difficulty":"zor","source":"Maksillofasyal Travmatoloji"},
    {"category_id":7,"question_text":"Dental implant için minimum kemik genişliği ne olmalıdır?","option_a":"3 mm","option_b":"6 mm","option_c":"10 mm","option_d":"15 mm","option_e":"20 mm","correct_answer":"B","explanation":"Standart çaplı (3.75-4mm) bir implant için kemik genişliğinin en az 6 mm olması gerekir. İmplantın her iki yanında en az 1 mm kemik kalması önerilir.","difficulty":"orta","source":"İmplantoloji"},
    {"category_id":7,"question_text":"Submandibular boşluk enfeksiyonunda en önemli risk nedir?","option_a":"Ses kısıklığı","option_b":"Hava yolu obstrüksiyonu (Ludwig anjini)","option_c":"Disfaji","option_d":"Trismus","option_e":"Deri fistülü","correct_answer":"B","explanation":"Ludwig anjini, bilateral submandibular, sublingual ve submental boşlukların enfeksiyonudur. Dil tabanı ve boyun şişliği ile hava yolu obstrüksiyonuna neden olabilir — acil müdahale gerektirir.","difficulty":"zor","source":"Oral Cerrahi"},
    {"category_id":7,"question_text":"Diş çekimi hangi durumda kontrendikedir?","option_a":"Kronik periodontitis","option_b":"Kontrolsüz diyabet ve akut enfeksiyon","option_c":"Kök kırığı","option_d":"Kist varlığı","option_e":"Ortodontik endikasyon","correct_answer":"B","explanation":"Kontrolsüz diyabet yara iyileşmesini bozar ve enfeksiyon riskini artırır. Akut enfeksiyon varlığında anestezi etkisiz kalabilir. Önce stabilizasyon ve enfeksiyon kontrolü gerekir.","difficulty":"orta","source":"Oral Cerrahi"},
    {"category_id":7,"question_text":"Antikoagülan kullanan hastada diş çekimi öncesi hangi test yapılmalıdır?","option_a":"Tam kan sayımı","option_b":"INR (International Normalized Ratio)","option_c":"Karaciğer fonksiyon testleri","option_d":"Böbrek fonksiyon testleri","option_e":"Tiroid fonksiyon testleri","correct_answer":"B","explanation":"Warfarin gibi antikoagülan kullanan hastalarda INR değeri kontrol edilmeli, genellikle INR<3.5 ise lokal hemostatik önlemlerle çekim yapılabilir.","difficulty":"orta","source":"Oral Cerrahi"},

    # ═══════════════════════════════════════
    # KATEGORİ 8: Restoratif Diş Tedavisi
    # ═══════════════════════════════════════
    {"category_id":8,"question_text":"Kompozit rezin restorasyonlarda asitleme (etching) işleminin amacı nedir?","option_a":"Minede mikro pörözite oluşturma","option_b":"Bakterileri öldürme","option_c":"Renk uyumu sağlama","option_d":"Pulpayı koruma","option_e":"Çürüğü temizleme","correct_answer":"A","explanation":"Fosforik asit (%37) ile asitleme, mine yüzeyinde mikro pöröziteler oluşturarak adeziv rezinin mine prizmaları arasına penetre olmasını ve mekanik bağlanmayı sağlar.","difficulty":"kolay","source":"Restoratif Diş Tedavisi"},
    {"category_id":8,"question_text":"Sınıf II amalgam kavitesinde matrix bandının kullanım amacı nedir?","option_a":"Isı izolasyonu","option_b":"Proksimal kontağı ve kontur oluşturma","option_c":"Pulpayı koruma","option_d":"Anestezi etkisini uzatma","option_e":"Çürük tespiti","correct_answer":"B","explanation":"Matrix bandı, Sınıf II kavitelerde eksik olan proksimal duvarın yerine geçerek dolgu materyalinin şekillendirilmesini ve proksimal kontağın sağlanmasını sağlar.","difficulty":"kolay","source":"Operatif Diş Hekimliği"},
    {"category_id":8,"question_text":"Cam iyonomer simanın en önemli avantajı nedir?","option_a":"Yüksek estetik","option_b":"Flor salınımı ve kimyasal bağlanma","option_c":"Yüksek aşınma direnci","option_d":"Kolay polisaj","option_e":"Düşük maliyet","correct_answer":"B","explanation":"Cam iyonomer siman diş dokusuna kimyasal olarak bağlanır ve uzun süre flor salınımı yaparak çürük önleyici etki gösterir. Bu iki özellik en büyük avantajıdır.","difficulty":"kolay","source":"Restoratif"},
    {"category_id":8,"question_text":"Derin çürük kavitesinde pulpaya en yakın bölgede hangi kaide materyali tercih edilir?","option_a":"Kompozit rezin","option_b":"Kalsiyum hidroksit","option_c":"Amalgam","option_d":"Silikon","option_e":"Çinko fosfat","correct_answer":"B","explanation":"Kalsiyum hidroksit, yüksek pH'ı sayesinde antibakteriyel etki gösterir ve reparatif dentin oluşumunu uyarır. Derin kavitelerde pulpaya yakın bölgede liner/kaide olarak kullanılır.","difficulty":"orta","source":"Restoratif"},
    {"category_id":8,"question_text":"İnley ve onley restorasyonlar arasındaki temel fark nedir?","option_a":"Kullanılan materyal farklıdır","option_b":"İnley tüberkülleri kapsamaz, onley en az bir tüberkülü kapsar","option_c":"İnley sadece ön dişlerde uygulanır","option_d":"Onley daha küçüktür","option_e":"Fark yoktur","correct_answer":"B","explanation":"İnley, kavite sınırları içinde kalır ve tüberkülleri kapsamaz. Onley ise en az bir tüberkülü (kasp) kapsayan daha geniş bir restorasyondur.","difficulty":"orta","source":"Restoratif"},
    {"category_id":8,"question_text":"Total-etch (tam asitleme) adeziv sistemlerde uygulama sırası nedir?","option_a":"Bond → Asit → Primer","option_b":"Asit → Primer → Bond","option_c":"Primer → Asit → Bond","option_d":"Bond → Primer → Asit","option_e":"Asit → Bond → Primer","correct_answer":"B","explanation":"Total-etch (4. ve 5. jenerasyon) adeziv sistemlerde sıra: 1) Fosforik asit ile asitleme, 2) Primer uygulaması, 3) Bonding ajan uygulaması. 5. jenerasyonda primer ve bond tek şişede birleştirilmiştir.","difficulty":"orta","source":"Adeziv Diş Hekimliği"},
    {"category_id":8,"question_text":"Kompozit polimerasyonunda 'C-faktör' ne anlama gelir?","option_a":"Renk faktörü","option_b":"Bağlı yüzey / serbest yüzey oranı (konfigürasyon faktörü)","option_c":"Basınç faktörü","option_d":"Sıcaklık katsayısı","option_e":"Çürük riski","correct_answer":"B","explanation":"C-faktör (konfigürasyon faktörü), kavitede kompozitin bağlandığı yüzeylerin serbest yüzeylere oranıdır. Yüksek C-faktör = yüksek polimerizasyon büzülme stresi = bağlanma başarısızlığı riski.","difficulty":"zor","source":"Restoratif"},
    {"category_id":8,"question_text":"Amalgam dolgunun avantajı nedir?","option_a":"Estetik görünüm","option_b":"Uzun ömür ve yüksek aşınma direnci","option_c":"Diş dokusuna bağlanma","option_d":"Flor salınımı","option_e":"Düşük termal iletkenlik","correct_answer":"B","explanation":"Amalgam, yüksek basınç dayanımı, aşınma direnci ve uzun klinik ömrü ile posterior dişlerde kanıtlanmış bir restoratif materyaldir. Ancak estetik değildir ve diş dokusuna kimyasal olarak bağlanmaz.","difficulty":"kolay","source":"Restoratif"},
]


def seed_database(session):
    """
    Veritabanına başlangıç verilerini yükler.
    İdempotent — zaten varsa tekrar eklemez.
    """
    from src.infrastructure.database.models import CategoryModel, QuestionModel

    # Kategori kontrolü
    existing = session.query(CategoryModel).count()
    if existing > 0:
        print("ℹ️  Seed data zaten mevcut, atlanıyor.")
        return

    # Kategorileri ekle
    for cat in CATEGORIES:
        session.add(CategoryModel(**cat))
    session.commit()
    print(f"✅ {len(CATEGORIES)} kategori eklendi.")

    # Soruları ekle
    for q in QUESTIONS:
        session.add(QuestionModel(**q))
    session.commit()
    print(f"✅ {len(QUESTIONS)} soru eklendi.")
